version: '2'
services:
  Clevo-Server:
    image: 'node:8.9'
    restart: always
    ports:
      - '1234:4000'
    volumes:
#      - './:/app:rw' # used for dev
      - 'clevo-server-dev-uswest:/app:rw' # dev
#      - 'clevo-server-dev:/app:rw' # staging
      - '/app/node_modules/' # make sure /app/node_modules is empty initially, and detach from oss
    environment:
      - 'PORT=4000'
      - 'MONGO_URI=mongodb://clevoUser:password@ds113505.mlab.com:13505/auth'
      - 'NODE_ENV=dev'
      - 'CLIENT_PORT=3000'
      - 'DEBUG=*,-babel,-*.test'
    labels:
      aliyun.routing.port_4000: clevo-server
      aliyun.scale: '2'
    command: bash -c "cd /app && npm install && npm run dev"
