version: '2'
services:
  Clevo-Server:
    image: 'node:8.9'
    restart: always
    ports:
      - '1234:4000'
    volumes:
      # - './:/tarDir:rw' # used for dev
      - 'clevo-server-dev-uswest:/tarDir:rw' # dev
#      - 'clevo-server-dev:/app:rw' # staging
    environment:
      - 'PORT=4000'
      - 'MONGO_URI=mongodb://clevoUser:password@ds113505.mlab.com:13505/auth'
      - 'NODE_ENV=dev'
      - 'CLIENT_PORT=3000'
      - 'DEBUG=*,-babel,-*.test'
    labels:
      aliyun.routing.port_4000: clevo-server
      aliyun.scale: '2'
    command: bash -c "mkdir -p application && cp tarDir/clevo-server-1.0.0.tgz /application && cd application/ && tar -xf clevo-server-1.0.0.tgz && cd package && node index.js"
