version: '2'
services:
  web:
    image: clevo/audio-formatting-service
    volumes:
      # - './app:/app:rw' # used for dev
      - 'clevo-audio-preprocessing-dev:/app:rw' # dev
      - '/app/node_modules/' # make sure /app/node_modules is empty initially, and detach from oss
    ports:
      - '3030:3030'
    labels:
      aliyun.routing.port_3030: audio-formatting
      aliyun.scale: '2'      
    command: bash -c "cd /app && npm install && node app.js"
    # command: tail -F anything
